#!/bin/sh
. slsupport.properties
_beName=$1
_beCPID=''
if [ -z "${_beName}" ]
then
        echo "Enter Backend Name"
else
	projFilePath=`echo -n $project_path$file_path | tr -d "\r"`
	scriptPath=`echo -n $project_path$script_path | tr -d "\r"`
	todayFolder=$(date +%m%d%y);

	echo "Maintenance Project "${scriptPath};
	## below script to check Recorder status if any recorder is up then skip the below steps else execute the below steps.
	backendType="";
	listerPort="";
	recordStartStopPort="";
	lstargetHost="";
	lstargetPort="";
	isCorrentBE='NO';

for _beDetails in `cat beList`;
    do
	var=$(echo $_beDetails | awk -F"#" '{print $1,$2,$3,$4,$5,$6,$7}')
	set -- $var
	backendName=$1;
	if [ "${_beName}" = $1 ]
	then
		backendType=$2;
		listerPort=$3;
		recordStartStopPort=$4;
		lstargetHost=$5;
		lstargetPort=$6;
		isCorrentBE='YES';
        fi
    done
if [ "$isCorrentBE" == "YES" ]
    then
	isRecorderFound='NO';
	for _bePID in `ps -ef | egrep -wi ${_beName}'_.*\.vsm' | grep -v grep | awk '{print $2}'`
	do
		 _beCPID=$(pgrep -P ${_bePID});
		 echo "${_beName} >>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
		 echo "${_beName} Main PID = "${_bePID};
		 echo "${_beName} Child PID = "${_beCPID};
		 echo "Backend Type = "${backendType};
		 echo "Lister Port = "${listerPort};
		 echo "Stop Signal Port = "${recordStartStopPort};
		 echo "Target Host = "${lstargetHost};
		 echo "Target Port = "${lstargetPort};
		 echo "RawTraffic File = ";
		 echo "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< ${_beName}";
		 echo "";
		if [ ! -z "$_bePID" ]
		then
			isRecorderFound='YES'
		fi
	done
	if [ "$isRecorderFound" == "NO" ]
	then
	   echo "Process Started .....Please wait....";
	   ## below script to Delete all recorder startup script
	   for  shFile in `ls $scriptPath/*.sh`
		do
		   rm $shFile
		done
  	   echo "Deleted all startup scripts ...";
	   ## below script to invoke multiRecorder Java to generate new Backend wise recorder startup script
	   java -jar MultipleRecorder.jar
	   sleep 1

	   echo "Re-Generated all startup scripts (MultipleRecorder Executed...)";

	   ## below script to  start all Backend wise Recorders by calling startAllRecorders.sh
	   sh $scriptPath"/start"${_beName}".sh" &
           #echo $scriptPath"/start"${_beName}".sh"

	   sleep 2
	   echo "${_beName} Recorder is started ...";

	   for _bePID in `ps -ef | egrep -wi ${_beName}'_.*\.vsm' | grep -v grep | awk '{print $2}'`
	   do
		_beCPID=$(pgrep -P ${_bePID});
		 echo "${_beName} >>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
		 echo "${_beName} Main PID = "${_bePID};
		 echo "${_beName} Child PID = "${_beCPID};
		 echo "Backend Type = "${backendType};
		 echo "Lister Port = "${listerPort};
		 echo "Stop Signal Port = "${recordStartStopPort};
		 echo "Target Host = "${lstargetHost};
		 echo "Target Port = "${lstargetPort};
		 echo "RawTraffic File = ";
		 echo "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< ${_beName}";
		 echo "";
		 if [ ! -z "$_bePID" ]
		 then
		     isRecorderFound='YES'
		 fi
	   done
	   echo "Process Completed ..."
	   echo "Above Recorders are up and running ..."
	else
           echo "${_beName} Recorder is already running,Please stop the recorder";
	fi
   else
     echo "${_beName} is not a Valid or Existing backend in beList Control File...";
   fi
fi

