#!/bin/sh
. slsupport.properties

projFilePath=`echo -n $project_path$file_path | tr -d "\r"`
scriptPath=`echo -n $project_path$script_path | tr -d "\r"`
todayFolder=$(date +%m%d%y);

echo "Maintenance Project "${scriptPath};
## below script to check Recorder status if any recorder is up then skip the below steps else execute the below steps.
isRecorderFound='NO';
    backendType="";
    listerPort="";
    recordStartStopPort="";
    lstargetHost="";
    lstargetPort="";
	
for _beDetails in `cat beList`;
do
	var=$(echo $_beDetails | awk -F"#" '{print $1,$2,$3,$4,$5,$6,$7}')
	set -- $var
	_beName=$1;
	backendType=$2;
	listerPort=$3;
	recordStartStopPort=$4;
	lstargetHost=$5;
	lstargetPort=$6;
	for _bePID in `ps -ef | egrep -wi ${_beName}'_.*\.vsm' | grep -v grep | awk '{print $2}'`
	do
	         _beCPID=$(pgrep -P ${_bePID});
		 echo "${_beName} >>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
		 echo "${_beName} Main PID = "${_bePID};
		 echo "${_beName} Child PID = "${_beCPID};
		 echo "Backend Type = "${backendType};
		 echo "Lister Port = "${listerPort};
		 echo "Stop Signal Port = "${recordStartStopPort};
		 echo "Target Host = "${lstargetHost};
		 echo "Target Port = "${lstargetPort};
		 echo "RawTraffic File = ";
		 echo "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< ${_beName}";
		 echo "";
		if [ ! -z "$_bePID" ]
                then
                    isRecorderFound='YES'
                fi
	done
    done
if [ "$isRecorderFound" == "NO" ]
then
   echo "Process Started .....Please wait....";

   ## below script to check Broker/Registry status & Stop/Start Broker/Registry
   isBrokerUp='NO';
   for _bePID in `ps -ef | egrep -wi 'lisa.agent.migrate.properties=false' | grep -v grep | awk '{print $2}'`
          do
            echo "Broker PID -->"${_bePID};
            #kill -9 ${_bePID};
   	    isBrokerUp='YES';
          done
    ## Start Broker-------------->
    if [ "$isBrokerUp" == "NO" ]
    then
        nohup java -jar /opt/app/t1eam4c1/Lisa7.5/agent/LisaAgent.jar  lisa.agent.migrate.properties=false  -b launch &
        echo "Broker Services are restarted ...";
    fi
	
   isRegistryUp='NO';
   for _bePID in `ps -ef | egrep -wi 'DLISA_LOG=registry.log' | grep -v grep | awk '{print $2}'`
          do
            echo "Registry PID -->"${_bePID};
            #kill -9 ${_bePID};
  	    isRegistryUp='YES';
          done
    ## Start Registry-------------->
    if [ "$isRegistryUp" == "NO" ]
    then
       nohup /opt/app/t1eam4c1/Lisa7.5/bin/./Registry &
       echo "Registry Services are restarted ...";
    fi
   
   ## below script to Delete all recorder startup script
    for  shFile in `ls $scriptPath/*.sh`
        do
           rm $shFile
        done
    echo "Deleted all startup scripts ...";
    ## below script to invoke multiRecorder Java to generate new Backend wise recorder startup script
    java -jar MultipleRecorder.jar
    sleep 10

    echo "Re-Generated all startup scripts (MultipleRecorder Executed...)";

    ## below script to  start all Backend wise Recorders by calling startAllRecorders.sh
    sh $scriptPath"/startAllRecorders.sh"
    sleep 20
    echo "All Recorders are started ...";

    backendType="";
    listerPort="";
    recordStartStopPort="";
    lstargetHost="";
    lstargetPort="";
	
    for _beDetails in `cat beList`;
	do
	var1=$(echo $_beDetails | awk -F"#" '{print $1,$2,$3,$4,$5,$6,$7}')
	set -- $var1
	_beName=$1;
	backendType=$2;
	listerPort=$3;
	recordStartStopPort=$4;
	lstargetHost=$5;
	lstargetPort=$6;
	for _bePID in `ps -ef | egrep -wi ${_beName}'_.*\.vsm' | grep -v grep | awk '{print $2}'`
	do
		_beCPID=$(pgrep -P ${_bePID});
		 echo "${_beName} >>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
		 echo "${_beName} Main PID = "${_bePID};
		 echo "${_beName} Child PID = "${_beCPID};
		 echo "Backend Type = "${backendType};
		 echo "Lister Port = "${listerPort};
		 echo "Stop Signal Port = "${recordStartStopPort};
		 echo "Target Host = "${lstargetHost};
		 echo "Target Port = "${lstargetPort};
		 echo "RawTraffic File = ";
		 echo "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< ${_beName}";
		 echo "";
	   if [ ! -z "$_bePID" ]
           then
               isRecorderFound='YES'
           fi
        done
    done
    echo "Process Completed ..."
    echo "Above Recorders are up and running ..."
else
   echo "Above listed BE Recorders are still running,Please stop the recorders ";
fi
