#!/bin/sh
. slsupport.properties
_beName=$1
_beCPID=''
if [ -z "${_beName}" ]
then
    echo "Enter Backend Name..."
else
    projFilePath=`echo -n $project_path$file_path | tr -d "\r"`
    wsFilePath=`echo -n $project_path$file_path$ws_path | tr -d "\r"`
    javaFilePath=`echo -n $project_path$file_path$java_path | tr -d "\r"`

    todayFolder=$(date +%m%d%y);
    echo ${projFilePath};
    ## below script to check Recorder status if any recorder is up then skip the below steps else execute the below steps.
    backendType="";
    listerPort="";
    recordStartStopPort="";
    lstargetHost="";
    lstargetPort="";
    isCorrentBE='NO';

    for _beDetails in `cat beList`;
    do
	var=$(echo $_beDetails | awk -F"#" '{print $1,$2,$3,$4,$5,$6,$7}')
	set -- $var
	backendName=$1;
	if [ "${_beName}" = $1 ]
	then
		backendType=$2;
		listerPort=$3;
		recordStartStopPort=$4;
		lstargetHost=$5;
		lstargetPort=$6;
		isCorrentBE='YES';
        fi
    done
    if [ "$isCorrentBE" == "YES" ]
    then
	isRecorderFound='NO'
	for _bePID in `ps -ef | egrep -wi ${_beName}'_.*\.vsm' | grep -v grep | awk '{print $2}'`
	do
		_beCPID=$(pgrep -P ${_bePID});
		 echo "${_beName} >>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
		 echo "${_beName} Main PID = "${_bePID};
		 echo "${_beName} Child PID = "${_beCPID};
		 echo "Backend Type = "${backendType};
		 echo "Lister Port = "${listerPort};
		 echo "Stop Signal Port = "${recordStartStopPort};
		 echo "Target Host = "${lstargetHost};
		 echo "Target Port = "${lstargetPort};
		 echo "RawTraffic File(s) = ";
		if [ "$backendType" == "Java" ]
                then   
                    ls -ltr $javaFilePath | awk '/:/ {print $5,$6,$7,$8,$9}'
                fi
		if [ "$backendType" == "WEBService" ]
                then  
                   ls -ltr $wsFilePath"/"${_beName}"/RawTraffic" | awk '/:/ {print $5,$6,$7,$8,$9}'
                fi 				 
                echo "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< ${_beName}";
	        echo "";
		if [ ! -z "$_bePID" ]
		then
			isRecorderFound='YES'
		fi
		done
		if [ "$isRecorderFound" == "YES" ]
		then
		   echo "Above ${_beName} recorder is going to stop...";
		   echo "Process Started .....Please wait....";

		   ## below script to stop the recorder by calling stopRecorder script
		   scriptPath=`echo -n $project_path$script_path | tr -d "\r"`
		   sh $scriptPath"/stop${_beName}.sh"
		   sleep 10
		   echo "${_beName} Recorder is stopped...";
		   echo "";

		   ## below script to kill all recorders main and child PIDs
			for _bePID in `ps -ef | egrep -wi ${_beName}'_.*\.vsm' | grep -v grep | awk '{print $2}'`
			do
				_beCPID=$(pgrep -P ${_bePID});
				kill -9 ${_bePID};
				kill -9 ${_beCPID};
			done
			sleep 10;
			echo "${_beName} Process ID's are killed..."
			echo "";
			echo "All previous days WEBSERVICES RawTraffic files are moved to corresponding date folders... ";
			echo "Stop process completed successfully...";
		else
		   echo "${_beName} Recorder is not up and running to STOP... ";
		fi
	else
	   echo "${_beName} is not Valid or Exist in beList Control File...";
	fi
fi
