#!/bin/sh
. slsupport.properties

    projFilePath=`echo -n $project_path$file_path | tr -d "\r"`
    todayFolder=$(date +%m%d%y);

    echo ${projFilePath};
    ##below script is used to add those files which are not added into SVN and svn commit with message
    path="$projFilePath"
    cd $path
    #for CURRENT in `find $projFilePath -name "*"`
    for CURRENT in `find . ! -name . -prune`
      do
        if [[ -d "$CURRENT" ]]
        then
          echo $CURRENT;
          CURRENT1=`echo $CURRENT | sed 's/^..//'`
          
          if [[ $CURRENT1 = *[!0-9]* ]]
          then 
              echo "Folder $CURRENT1 is not checked-in SVN";
          else 
              svn add $CURRENT;
              svn commit $CURRENT -m "Daily maintenance, committed through automatic script on  `date +'%m/%d/%Y %H:%M:%S'`";
          fi
        fi
      done

   #SVN Add
   #    COUNT=`svn status   | grep ^?  |wc -l`
   #    until [ $COUNT -lt "0" ]
   #          do
   #              CURRENT=`svn status  | grep ^? |awk {'print $2'} | head -$COUNT | tail -1`
          #       svn add $CURRENT
   #              echo "FILE $CURRENT ADDED  **** "
   #              COUNT=`expr $COUNT - 1 `
   #          done
   #SVN Commit
   # svn commit -m "Daily maintenance committed through automatic script on  `date +'%m/%d/%Y %H:%M:%S'`"
      echo "svn Committed at `date +'%m/%d/%Y %H:%M:%S'`";
