#!/bin/sh
## below script to check Broker status
   isBrokerUp='NO';
   for _bePID in `ps -ef | egrep -wi 'lisa.agent.migrate.properties=false' | grep -v grep | awk '{print $2}'`
   do
       echo "Broker is up and running ...";
       echo "Broker PID -->"${_bePID};
       isBrokerUp='YES'; 
   done
if [ "$isBrokerUp" == "NO" ]
    then
      echo "Broker is not Up and Running...";
fi
