#!/bin/sh
isBrokerUp='NO';
for _bePID in `ps -ef | egrep -wi 'lisa.agent.migrate.properties=false' | grep -v grep | awk '{print $2}'`
do
    echo "Broker PID -->"${_bePID};
    isBrokerUp='YES';
    echo "Broker already up and running...";
done
## Start Broker-------------->
if [ "$isBrokerUp" == "NO" ]
then
    nohup java -jar $HOME/Lisa7.5/agent/LisaAgent.jar  lisa.agent.migrate.properties=false  -b launch &
    echo "Broker Services are restarted ...";
fi
