#!/bin/sh
## below script to check Registry status
isRegistryUp='NO';
for _bePID in `ps -ef | egrep -wi 'DLISA_LOG=registry.log' | grep -v grep | awk '{print $2}'`
    do
      echo "Registry PID -->"${_bePID};
      echo "Registry Services up and running...";
      isRegistryUp='YES';
    done
if [ "$isRegistryUp" == "NO" ]
    then
      echo "Registry is not Up and Running...";
fi
