#!/bin/sh
isRegistryUp='NO';
for _bePID in `ps -ef | egrep -wi 'DLISA_LOG=registry.log' | grep -v grep | awk '{print $2}'`
do
    echo "Registry PID -->"${_bePID};
    isRegistryUp='YES';
    echo "Registry Service already up and running ...";
done
## Start Registry-------------->
if [ "$isRegistryUp" == "NO" ]
then
   nohup $HOME/Lisa7.5/bin/./RegistryService start -Xms2048m -Xmx2048m &
   echo "Registry Service started ...";
fi
