#!/usr/bin/ksh
JAVA_HOME=/opt/app/t1eam4c11/CA/DevTest/jre/bin
export JAVA_HOME
echo 'kill -9 ' $$ > svFELogReaderAutoKill
chmod 777 svFELogReaderAutoKill
ant OlamLogParser
while true
do
   sleep 30m
   ant OlamLogParser
done

