<?xml version="1.0" encoding="UTF-8"?>
<!-- =========================================================================

                         AT&T Proprietary (Internal Use Only)                                           

  Not for use or disclosure outside the AT&T companies except under written agreement

  (c) 2007 AT&T Intellectual Property. All rights reserved. AT&T and

        the AT&T logo are trademarks of AT&T Intellectual Property.

======================================================================= -->
<wsdl:definitions xmlns:mhd='http://csi.cingular.com/CSI/Namespaces/OrderAndSubscriptionManagementMobility/InfrastructureCommon/Types/Public/MessageHeader.xsd' xmlns:n1='http://csi.cingular.com/CSI/Namespaces/Container/Public/InquireUnifiedCustomerLoginProfileResponse.xsd' xmlns:n0='http://csi.cingular.com/CSI/Namespaces/Container/Public/InquireUnifiedCustomerLoginProfileRequest.xsd' targetNamespace='http://csi.cingular.com/CSI/Namespaces/OrderAndSubscriptionManagementMobility/232.0/wsdl/OrderAndSubscriptionManagementMobilityCSI.wsdl' xmlns:xs='http://www.w3.org/2001/XMLSchema' xmlns:sfd='http://csi.cingular.com/CSI/Namespaces/OrderAndSubscriptionManagementMobility/InfrastructureCommon/Types/Public/SoapFaultDetails.xsd' xmlns:soap='http://schemas.xmlsoap.org/wsdl/soap/' xmlns:tns='http://csi.cingular.com/CSI/Namespaces/OrderAndSubscriptionManagementMobility/232.0/wsdl/OrderAndSubscriptionManagementMobilityCSI.wsdl' xmlns:wsdl='http://schemas.xmlsoap.org/wsdl/'>
  <wsdl:types>
    <xs:schema targetNamespace='http://csi.cingular.com/CSI/Namespaces/OrderAndSubscriptionManagementMobility/InfrastructureCommon/Types/Public/MessageHeader.xsd' elementFormDefault='qualified'>
      <xs:include schemaLocation='MessageHeader-CDM.xsd' />
    </xs:schema>
    <xs:schema targetNamespace='http://csi.cingular.com/CSI/Namespaces/OrderAndSubscriptionManagementMobility/InfrastructureCommon/Types/Public/SoapFaultDetails.xsd' elementFormDefault='qualified'>
      <xs:include schemaLocation='SoapFaultDetails-CDM.xsd' />
    </xs:schema>
    <xs:schema targetNamespace='http://csi.cingular.com/CSI/Namespaces/Container/Public/InquireUnifiedCustomerLoginProfileRequest.xsd' elementFormDefault='qualified'>
      <xs:include schemaLocation='InquireUnifiedCustomerLoginProfileRequest.xsd' />
    </xs:schema>
    <xs:schema targetNamespace='http://csi.cingular.com/CSI/Namespaces/Container/Public/InquireUnifiedCustomerLoginProfileResponse.xsd' elementFormDefault='qualified'>
      <xs:include schemaLocation='InquireUnifiedCustomerLoginProfileResponse.xsd' />
    </xs:schema>
  </wsdl:types>
  <wsdl:message name='CSIApplicationException'>
    <wsdl:part name='fault' element='sfd:CSIApplicationException' />
  </wsdl:message>
  <wsdl:message name='InquireUnifiedCustomerLoginProfileRequest'>
    <wsdl:part name='MessageHeader' element='mhd:MessageHeader' />
    <wsdl:part name='InquireUnifiedCustomerLoginProfileRequest' element='n0:InquireUnifiedCustomerLoginProfileRequest' />
  </wsdl:message>
  <wsdl:message name='InquireUnifiedCustomerLoginProfileResponse'>
    <wsdl:part name='MessageHeader' element='mhd:MessageHeader' />
    <wsdl:part name='InquireUnifiedCustomerLoginProfileResponse' element='n1:InquireUnifiedCustomerLoginProfileResponse' />
  </wsdl:message>
  <wsdl:portType name='InquireUnifiedCustomerLoginProfilePortType'>
    <wsdl:operation name='InquireUnifiedCustomerLoginProfile'>
      <wsdl:input message='tns:InquireUnifiedCustomerLoginProfileRequest' />
      <wsdl:output message='tns:InquireUnifiedCustomerLoginProfileResponse' />
      <wsdl:fault name='fault' message='tns:CSIApplicationException' />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name='InquireUnifiedCustomerLoginProfileSoapHttpBinding' type='tns:InquireUnifiedCustomerLoginProfilePortType'>
    <soap:binding style='document' transport='http://schemas.xmlsoap.org/soap/http' />
    <wsdl:operation name='InquireUnifiedCustomerLoginProfile'>
      <soap:operation soapAction='' style='document' />
      <wsdl:input>
        <soap:header message='tns:InquireUnifiedCustomerLoginProfileRequest' part='MessageHeader' use='literal' />
        <soap:body parts='InquireUnifiedCustomerLoginProfileRequest' use='literal' />
      </wsdl:input>
      <wsdl:output>
        <soap:header message='tns:InquireUnifiedCustomerLoginProfileResponse' part='MessageHeader' use='literal' />
        <soap:body parts='InquireUnifiedCustomerLoginProfileResponse' use='literal' />
      </wsdl:output>
      <wsdl:fault name='fault'>
        <soap:fault name='fault' use='literal' />
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name='OrderAndSubscriptionManagementMobilityService'>
    <wsdl:port name='InquireUnifiedCustomerLoginProfileSoapHttpPort' binding='tns:InquireUnifiedCustomerLoginProfileSoapHttpBinding'>
      <soap:address location='https://qa9-csiwwwi-tn.edc.cingular.net:19443/Services/com/cingular/csi/ccr/InquireUnifiedCustomerLoginProfile.jws' />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>