<?xml version="1.0" ?>

<TestCase name="ws_security" version="5">

<meta><create version="0.0" buildNumber="0.0.0.0" author="cam" date="11/17/2009" host="sloth"  /><lastEdited version="0.0" buildNumber="0.0.0.0" author="cam" date="02/10/2010" host="sloth"  /></meta>

<id>75c74039</id>
<Documentation>Shows how to use signed and encrypted SOAP messages. The first two steps should succeed and the last two steps should fail (the calls are the same but the web service will not accept messages that are not encrypted or signed)</Documentation>
<IsInProject>true</IsInProject>
<sig>ZWQ9NSZ0Y3Y9NSZsaXNhdj0wLjAgKDAuMC4wLjAgdW5zdXBwb3J0ZWQgZGV2IHZlcnNpb24pJm5vZGVzPTE1MDg1Mjc3MDk=</sig>
<subprocess>false</subprocess>

<initState>
</initState>

<resultState>
</resultState>

    <Node name="Step 1: Test XML Signature" log=""
          type="com.itko.lisa.dynexec.axis.WebServiceNode" 
          version="1" 
          think="0" 
          useFilters="true" 
          quiet="false" 
          next="Step 2: Test XML Encryption" > 

<Documentation>We sign the SOAP messages using a keystore - {{LISA_PROJ_ROOT}}/Data/keystores/keystore.jks&#10;&#10;See the advanced tab of the WS call</Documentation>

      <!-- Assertions -->
<CheckResult assertTrue="true" name="Any Exception Then Fail" type="com.itko.lisa.dynexec.CheckInvocationEx">
<log>Assert [Any Exception Then Fail] fired true of type Assert on Invocation Exception</log>
<then>fail</then>
<valueToAssertKey></valueToAssertKey>
        <param>.*</param>
</CheckResult>

<className>com.itko.lisa.wsgen.SignedCalculatorService.CalculatorServiceLocator</className>
<onExNode>abort</onExNode>
<WSDL>http://{{WSSERVER}}:{{WSPORT}}/itko-examples/services/SignedCalculatorService?wsdl</WSDL>
<Package>com.itko.lisa.wsgen.SignedCalculatorService</Package>
<ClientJar>SignedCalculatorService.jar</ClientJar>
<SOAPBindAddr>http://{{WSSERVER}}:{{WSPORT}}/itko-examples/services/SignedCalculatorService</SOAPBindAddr>
<objStream>
<DynObject>
<type>com.itko.lisa.dynexec.ComplexObj</type>
<serialNum>0</serialNum>
<array>false</array>
<className>com.itko.lisa.wsgen.SignedCalculatorService.CalculatorServiceLocator</className>
<complex>true</complex>
<interface>false</interface>
<null>false</null>
<void>false</void>
<simple>false</simple>
<useprop>false</useprop>
<Setters>
</Setters>
<Call>
<methodName>getSignedCalculatorService</methodName>
<retClassName>com.itko.lisa.wsgen.SignedCalculatorService.Calculator</retClassName>
<actParamClassName>java.net.URL</actParamClassName>
<paramClassName>java.net.URL</paramClassName>
<exClassName>javax.xml.rpc.ServiceException</exClassName>
<param>
<DynObject>
<type>com.itko.lisa.dynexec.ComplexObj</type>
<serialNum>3</serialNum>
<array>false</array>
<className>java.net.URL</className>
<complex>true</complex>
<interface>false</interface>
<null>false</null>
<void>false</void>
<simple>false</simple>
<useprop>true</useprop>
<propKey>itkolisa.WebServiceNode.hiddenBindAddrKey</propKey>
<Setters>
</Setters>
</DynObject>
</param>
<result>
<DynObject>
<type>com.itko.lisa.dynexec.ComplexObj</type>
<serialNum>4</serialNum>
<array>false</array>
<className>com.itko.lisa.wsgen.SignedCalculatorService.SignedCalculatorServiceSoapBindingStub</className>
<complex>true</complex>
<interface>false</interface>
<null>false</null>
<void>false</void>
<simple>false</simple>
<useprop>false</useprop>
<Setters>
</Setters>
<Call>
<methodName>add</methodName>
<retClassName>java.lang.Integer</retClassName>
<actParamClassName>int</actParamClassName>
<actParamClassName>int</actParamClassName>
<paramClassName>java.lang.Integer</paramClassName>
<paramClassName>java.lang.Integer</paramClassName>
<exClassName>java.rmi.RemoteException</exClassName>
<param>
<DynObject>
<type>com.itko.lisa.dynexec.SimpleObj</type>
<serialNum>6</serialNum>
<array>false</array>
<className>java.lang.Integer</className>
<complex>false</complex>
<interface>false</interface>
<null>false</null>
<void>false</void>
<simple>true</simple>
<useprop>false</useprop>
<simpleVal>5</simpleVal>
</DynObject>
</param>
<param>
<DynObject>
<type>com.itko.lisa.dynexec.SimpleObj</type>
<serialNum>7</serialNum>
<array>false</array>
<className>java.lang.Integer</className>
<complex>false</complex>
<interface>false</interface>
<null>false</null>
<void>false</void>
<simple>true</simple>
<useprop>false</useprop>
<simpleVal>4</simpleVal>
</DynObject>
</param>
<result>
<DynObject>
<type>com.itko.lisa.dynexec.SimpleObj</type>
<serialNum>5</serialNum>
<array>false</array>
<className>java.lang.Integer</className>
<complex>false</complex>
<interface>false</interface>
<null>false</null>
<void>false</void>
<simple>true</simple>
<useprop>false</useprop>
<simpleVal>9</simpleVal>
</DynObject>
</result>
<isCallMade>false</isCallMade>
</Call>
</DynObject>
</result>
<isCallMade>false</isCallMade>
</Call>
</DynObject>
</objStream>
<wsGlobalInfo>
<soapVersionUri>1.1</soapVersionUri>
<httpVersionUri>1.1</httpVersionUri>
<webMethodUri>POST</webMethodUri>
<mtom>false</mtom>
<dontSendRequest>false</dontSendRequest>
<dontDeserialze>false</dontDeserialze>
<allowNonNillable>false</allowNonNillable>
<callTimeout>600000</callTimeout>
<wsi-check-wsdl>false</wsi-check-wsdl>
<wsi-check-msg>false</wsi-check-msg>
<wsi-display-type>notPassed</wsi-display-type>
<wsi-on-fail>continue</wsi-on-fail>
<ssl-keystore-file></ssl-keystore-file>
<ssl-keystore-password-enc>f5504e2d23a7888253a27e8ef52607d8</ssl-keystore-password-enc>
</wsGlobalInfo>
<wss4jInfo>
<version>5</version>
<wssecurity>
<isSend>true</isSend>
<must>false</must>
<timestamp2>
<enabled>true</enabled>
<useMsTimestamp>true</useMsTimestamp>
<ttl>300</ttl>
</timestamp2>
<usernameToken>
<enabled>false</enabled>
<type>PasswordText</type>
<signed>false</signed>
<nonce>true</nonce>
<craeted>true</craeted>
<useMsTimestamp>true</useMsTimestamp>
</usernameToken>
<signature>
<enabled>true</enabled>
<file>{{LISA_PROJ_ROOT}}/Data/keystores/keystore.jks</file>
<type>jks</type>
<password-encr>d32b9ba6faca78de7b32314e43c15b4f</password-encr>
<defaultalias>test</defaultalias>
<alias-pass-encr>d32b9ba6faca78de7b32314e43c15b4f</alias-pass-encr>
<keyId>IssuerSerial</keyId>
<algo>http://www.w3.org/2000/09/xmldsig#dsa-sha1</algo>
</signature>
<encryption>
<enabled>false</enabled>
<type>jks</type>
<password-encr>f5504e2d23a7888253a27e8ef52607d8</password-encr>
<alias-pass-encr>f5504e2d23a7888253a27e8ef52607d8</alias-pass-encr>
<keyId>IssuerSerial</keyId>
<algo>http://www.w3.org/2001/04/xmlenc#aes128-cbc</algo>
<transport>http://www.w3.org/2001/04/xmlenc#rsa-1_5</transport>
</encryption>
</wssecurity>
<wssecurity>
<isSend>false</isSend>
<must>false</must>
</wssecurity>
<wsi-bsp>false</wsi-bsp>
</wss4jInfo>
<GenericHeader>
<ns>
</ns>
<xml></xml>
</GenericHeader>
<wsaInfo>
<useAddressing>false</useAddressing>
<must>false</must>
<to></to>
<toOverride>false</toOverride>
<toDefault>true</toDefault>
<from></from>
<fromOverride>false</fromOverride>
<fromDefault>true</fromDefault>
<action></action>
<actionOverride>false</actionOverride>
<actionDefault>true</actionDefault>
<msgid></msgid>
<msgidOverride>false</msgidOverride>
<msgidDefault>true</msgidDefault>
<replyTo></replyTo>
<replyToOverride>false</replyToOverride>
<faultTo></faultTo>
<faulttToOverride>false</faulttToOverride>
<addressingVersion>http://www.w3.org/2005/08/addressing</addressingVersion>
</wsaInfo>
<customHTTPHeaderInfo>
</customHTTPHeaderInfo>
<useDefaultNamespace>true</useDefaultNamespace>
<forceNoWrap>false</forceNoWrap>
<uddi-lookup>false</uddi-lookup>
    </Node>


    <Node name="Step 2: Test XML Encryption" log=""
          type="com.itko.lisa.dynexec.axis.WebServiceNode" 
          version="1" 
          think="0" 
          useFilters="true" 
          quiet="false" 
          next="Step 3: Fail: Document Not Encrypted" > 

<Documentation>We encyrpt the SOAP request using AES 128-bit encryption</Documentation>

      <!-- Assertions -->
<CheckResult assertTrue="true" name="Any Exception Then Fail" type="com.itko.lisa.dynexec.CheckInvocationEx">
<log>Assert [Any Exception Then Fail] fired true of type Assert on Invocation Exception</log>
<then>fail</then>
<valueToAssertKey></valueToAssertKey>
        <param>.*</param>
</CheckResult>

<className>com.itko.lisa.wsgen.EncryptedCalculatorService.CalculatorServiceLocator</className>
<onExNode>abort</onExNode>
<WSDL>http://{{WSSERVER}}:{{WSPORT}}/itko-examples/services/EncryptedCalculatorService?wsdl</WSDL>
<Package>com.itko.lisa.wsgen.EncryptedCalculatorService</Package>
<ClientJar>EncryptedCalculatorService.jar</ClientJar>
<SOAPBindAddr>http://{{WSSERVER}}:{{WSPORT}}/itko-examples/services/EncryptedCalculatorService</SOAPBindAddr>
<objStream>
<DynObject>
<type>com.itko.lisa.dynexec.ComplexObj</type>
<serialNum>17</serialNum>
<array>false</array>
<className>com.itko.lisa.wsgen.EncryptedCalculatorService.CalculatorServiceLocator</className>
<complex>true</complex>
<interface>false</interface>
<null>false</null>
<void>false</void>
<simple>false</simple>
<useprop>false</useprop>
<Setters>
</Setters>
<Call>
<methodName>getEncryptedCalculatorService</methodName>
<retClassName>com.itko.lisa.wsgen.EncryptedCalculatorService.Calculator</retClassName>
<actParamClassName>java.net.URL</actParamClassName>
<paramClassName>java.net.URL</paramClassName>
<exClassName>javax.xml.rpc.ServiceException</exClassName>
<param>
<DynObject>
<type>com.itko.lisa.dynexec.ComplexObj</type>
<serialNum>20</serialNum>
<array>false</array>
<className>java.net.URL</className>
<complex>true</complex>
<interface>false</interface>
<null>false</null>
<void>false</void>
<simple>false</simple>
<useprop>true</useprop>
<propKey>itkolisa.WebServiceNode.hiddenBindAddrKey</propKey>
<Setters>
</Setters>
</DynObject>
</param>
<result>
<DynObject>
<type>com.itko.lisa.dynexec.ComplexObj</type>
<serialNum>21</serialNum>
<array>false</array>
<className>com.itko.lisa.wsgen.EncryptedCalculatorService.EncryptedCalculatorServiceSoapBindingStub</className>
<complex>true</complex>
<interface>false</interface>
<null>false</null>
<void>false</void>
<simple>false</simple>
<useprop>false</useprop>
<Setters>
</Setters>
<Call>
<methodName>add</methodName>
<retClassName>java.lang.Integer</retClassName>
<actParamClassName>int</actParamClassName>
<actParamClassName>int</actParamClassName>
<paramClassName>java.lang.Integer</paramClassName>
<paramClassName>java.lang.Integer</paramClassName>
<exClassName>java.rmi.RemoteException</exClassName>
<param>
<DynObject>
<type>com.itko.lisa.dynexec.SimpleObj</type>
<serialNum>23</serialNum>
<array>false</array>
<className>java.lang.Integer</className>
<complex>false</complex>
<interface>false</interface>
<null>false</null>
<void>false</void>
<simple>true</simple>
<useprop>false</useprop>
<simpleVal>6</simpleVal>
</DynObject>
</param>
<param>
<DynObject>
<type>com.itko.lisa.dynexec.SimpleObj</type>
<serialNum>24</serialNum>
<array>false</array>
<className>java.lang.Integer</className>
<complex>false</complex>
<interface>false</interface>
<null>false</null>
<void>false</void>
<simple>true</simple>
<useprop>false</useprop>
<simpleVal>7</simpleVal>
</DynObject>
</param>
<result>
<DynObject>
<type>com.itko.lisa.dynexec.SimpleObj</type>
<serialNum>22</serialNum>
<array>false</array>
<className>java.lang.Integer</className>
<complex>false</complex>
<interface>false</interface>
<null>false</null>
<void>false</void>
<simple>true</simple>
<useprop>false</useprop>
<simpleVal>13</simpleVal>
</DynObject>
</result>
<isCallMade>false</isCallMade>
</Call>
</DynObject>
</result>
<isCallMade>false</isCallMade>
</Call>
</DynObject>
</objStream>
<wsGlobalInfo>
<soapVersionUri>1.1</soapVersionUri>
<httpVersionUri>1.1</httpVersionUri>
<webMethodUri>POST</webMethodUri>
<mtom>false</mtom>
<dontSendRequest>false</dontSendRequest>
<dontDeserialze>false</dontDeserialze>
<allowNonNillable>false</allowNonNillable>
<callTimeout>600000</callTimeout>
<wsi-check-wsdl>false</wsi-check-wsdl>
<wsi-check-msg>false</wsi-check-msg>
<wsi-display-type>notPassed</wsi-display-type>
<wsi-on-fail>continue</wsi-on-fail>
<ssl-keystore-file></ssl-keystore-file>
<ssl-keystore-password-enc>f5504e2d23a7888253a27e8ef52607d8</ssl-keystore-password-enc>
</wsGlobalInfo>
<wss4jInfo>
<version>5</version>
<wssecurity>
<isSend>true</isSend>
<must>false</must>
<timestamp2>
<enabled>true</enabled>
<useMsTimestamp>true</useMsTimestamp>
<ttl>300</ttl>
</timestamp2>
<usernameToken>
<enabled>false</enabled>
<type>PasswordText</type>
<signed>false</signed>
<nonce>true</nonce>
<craeted>true</craeted>
<useMsTimestamp>true</useMsTimestamp>
</usernameToken>
<signature>
<enabled>false</enabled>
<type>jks</type>
<password-encr>f5504e2d23a7888253a27e8ef52607d8</password-encr>
<alias-pass-encr>f5504e2d23a7888253a27e8ef52607d8</alias-pass-encr>
<keyId>IssuerSerial</keyId>
<algo>http://www.w3.org/2000/09/xmldsig#rsa-sha1</algo>
</signature>
<encryption>
<enabled>true</enabled>
<file>{{LISA_PROJ_ROOT}}/Data/keystores/myout.p12</file>
<type>pkcs12</type>
<password-encr>9839f65d0802b8cf48da5c1b095a0daa</password-encr>
<defaultalias>16c73ab6-b892-458f-abf5-2f875f74882e</defaultalias>
<alias-pass-encr>f5504e2d23a7888253a27e8ef52607d8</alias-pass-encr>
<keyId>IssuerSerial</keyId>
<algo>http://www.w3.org/2001/04/xmlenc#aes128-cbc</algo>
<transport>http://www.w3.org/2001/04/xmlenc#rsa-1_5</transport>
</encryption>
</wssecurity>
<wssecurity>
<isSend>false</isSend>
<must>false</must>
</wssecurity>
<wsi-bsp>false</wsi-bsp>
</wss4jInfo>
<GenericHeader>
<ns>
</ns>
<xml></xml>
</GenericHeader>
<wsaInfo>
<useAddressing>false</useAddressing>
<must>false</must>
<to></to>
<toOverride>false</toOverride>
<toDefault>true</toDefault>
<from></from>
<fromOverride>false</fromOverride>
<fromDefault>true</fromDefault>
<action></action>
<actionOverride>false</actionOverride>
<actionDefault>true</actionDefault>
<msgid></msgid>
<msgidOverride>false</msgidOverride>
<msgidDefault>true</msgidDefault>
<replyTo></replyTo>
<replyToOverride>false</replyToOverride>
<faultTo></faultTo>
<faulttToOverride>false</faulttToOverride>
<addressingVersion>http://www.w3.org/2005/08/addressing</addressingVersion>
</wsaInfo>
<customHTTPHeaderInfo>
</customHTTPHeaderInfo>
<useDefaultNamespace>true</useDefaultNamespace>
<forceNoWrap>false</forceNoWrap>
<uddi-lookup>false</uddi-lookup>
    </Node>


    <Node name="Step 3: Fail: Document Not Encrypted" log=""
          type="com.itko.lisa.dynexec.axis.WebServiceNode" 
          version="1" 
          think="0" 
          useFilters="true" 
          quiet="false" 
          next="fail" > 

<Documentation>This step is designed to fail because we send an unencrypted SOAP request</Documentation>

      <!-- Assertions -->
<CheckResult assertTrue="true" name="Any Exception Then Fail" type="com.itko.lisa.dynexec.CheckInvocationEx">
<log>Assert [Any Exception Then Fail] fired true of type Assert on Invocation Exception</log>
<then>fail</then>
<valueToAssertKey></valueToAssertKey>
        <param>.*</param>
</CheckResult>

<className>com.itko.lisa.wsgen.EncryptedCalculatorService.CalculatorServiceLocator</className>
<onExNode>Step 4: Fail: Missing Signature</onExNode>
<WSDL>http://{{WSSERVER}}:{{WSPORT}}/itko-examples/services/EncryptedCalculatorService?wsdl</WSDL>
<Package>com.itko.lisa.wsgen.EncryptedCalculatorService</Package>
<ClientJar>EncryptedCalculatorService.jar</ClientJar>
<SOAPBindAddr>http://{{WSSERVER}}:{{WSPORT}}/itko-examples/services/EncryptedCalculatorService</SOAPBindAddr>
<objStream>
<DynObject>
<type>com.itko.lisa.dynexec.ComplexObj</type>
<serialNum>17</serialNum>
<array>false</array>
<className>com.itko.lisa.wsgen.EncryptedCalculatorService.CalculatorServiceLocator</className>
<complex>true</complex>
<interface>false</interface>
<null>false</null>
<void>false</void>
<simple>false</simple>
<useprop>false</useprop>
<Setters>
</Setters>
<Call>
<methodName>getEncryptedCalculatorService</methodName>
<retClassName>com.itko.lisa.wsgen.EncryptedCalculatorService.Calculator</retClassName>
<actParamClassName>java.net.URL</actParamClassName>
<paramClassName>java.net.URL</paramClassName>
<exClassName>javax.xml.rpc.ServiceException</exClassName>
<param>
<DynObject>
<type>com.itko.lisa.dynexec.ComplexObj</type>
<serialNum>20</serialNum>
<array>false</array>
<className>java.net.URL</className>
<complex>true</complex>
<interface>false</interface>
<null>false</null>
<void>false</void>
<simple>false</simple>
<useprop>true</useprop>
<propKey>itkolisa.WebServiceNode.hiddenBindAddrKey</propKey>
<Setters>
</Setters>
</DynObject>
</param>
<result>
<DynObject>
<type>com.itko.lisa.dynexec.ComplexObj</type>
<serialNum>21</serialNum>
<array>false</array>
<className>com.itko.lisa.wsgen.EncryptedCalculatorService.EncryptedCalculatorServiceSoapBindingStub</className>
<complex>true</complex>
<interface>false</interface>
<null>false</null>
<void>false</void>
<simple>false</simple>
<useprop>false</useprop>
<Setters>
</Setters>
<Call>
<methodName>add</methodName>
<retClassName>java.lang.Integer</retClassName>
<actParamClassName>int</actParamClassName>
<actParamClassName>int</actParamClassName>
<paramClassName>java.lang.Integer</paramClassName>
<paramClassName>java.lang.Integer</paramClassName>
<exClassName>java.rmi.RemoteException</exClassName>
<param>
<DynObject>
<type>com.itko.lisa.dynexec.SimpleObj</type>
<serialNum>23</serialNum>
<array>false</array>
<className>java.lang.Integer</className>
<complex>false</complex>
<interface>false</interface>
<null>false</null>
<void>false</void>
<simple>true</simple>
<useprop>false</useprop>
<simpleVal>2</simpleVal>
</DynObject>
</param>
<param>
<DynObject>
<type>com.itko.lisa.dynexec.SimpleObj</type>
<serialNum>24</serialNum>
<array>false</array>
<className>java.lang.Integer</className>
<complex>false</complex>
<interface>false</interface>
<null>false</null>
<void>false</void>
<simple>true</simple>
<useprop>false</useprop>
<simpleVal>3</simpleVal>
</DynObject>
</param>
<result>
<DynObject>
<type>com.itko.lisa.dynexec.SimpleObj</type>
<serialNum>22</serialNum>
<array>false</array>
<className>java.lang.Integer</className>
<complex>false</complex>
<interface>false</interface>
<null>false</null>
<void>false</void>
<simple>true</simple>
<useprop>false</useprop>
<simpleVal>13</simpleVal>
</DynObject>
</result>
<isCallMade>false</isCallMade>
</Call>
</DynObject>
</result>
<isCallMade>false</isCallMade>
</Call>
</DynObject>
</objStream>
<wsGlobalInfo>
<soapVersionUri>1.1</soapVersionUri>
<httpVersionUri>1.1</httpVersionUri>
<webMethodUri>POST</webMethodUri>
<mtom>false</mtom>
<dontSendRequest>false</dontSendRequest>
<dontDeserialze>false</dontDeserialze>
<allowNonNillable>false</allowNonNillable>
<callTimeout>600000</callTimeout>
<wsi-check-wsdl>false</wsi-check-wsdl>
<wsi-check-msg>false</wsi-check-msg>
<wsi-display-type>notPassed</wsi-display-type>
<wsi-on-fail>continue</wsi-on-fail>
<ssl-keystore-file></ssl-keystore-file>
<ssl-keystore-password-enc>f5504e2d23a7888253a27e8ef52607d8</ssl-keystore-password-enc>
</wsGlobalInfo>
<wss4jInfo>
<version>5</version>
<wssecurity>
<isSend>true</isSend>
<must>false</must>
<timestamp2>
<enabled>false</enabled>
<useMsTimestamp>true</useMsTimestamp>
<ttl>300</ttl>
</timestamp2>
<usernameToken>
<enabled>false</enabled>
<type>PasswordText</type>
<signed>false</signed>
<nonce>true</nonce>
<craeted>true</craeted>
<useMsTimestamp>true</useMsTimestamp>
</usernameToken>
<signature>
<enabled>false</enabled>
<type>jks</type>
<password-encr>f5504e2d23a7888253a27e8ef52607d8</password-encr>
<alias-pass-encr>f5504e2d23a7888253a27e8ef52607d8</alias-pass-encr>
<keyId>IssuerSerial</keyId>
<algo>http://www.w3.org/2000/09/xmldsig#rsa-sha1</algo>
</signature>
<encryption>
<enabled>false</enabled>
<file>{{LISA_PROJ_ROOT}}/Data/keystores/myout.p12</file>
<type>pkcs12</type>
<password-encr>9839f65d0802b8cf48da5c1b095a0daa</password-encr>
<defaultalias>16c73ab6-b892-458f-abf5-2f875f74882e</defaultalias>
<alias-pass-encr>f5504e2d23a7888253a27e8ef52607d8</alias-pass-encr>
<keyId>IssuerSerial</keyId>
<algo>http://www.w3.org/2001/04/xmlenc#aes128-cbc</algo>
<transport>http://www.w3.org/2001/04/xmlenc#rsa-1_5</transport>
</encryption>
</wssecurity>
<wssecurity>
<isSend>false</isSend>
<must>false</must>
</wssecurity>
<wsi-bsp>false</wsi-bsp>
</wss4jInfo>
<GenericHeader>
<ns>
</ns>
<xml></xml>
</GenericHeader>
<wsaInfo>
<useAddressing>false</useAddressing>
<must>false</must>
<to></to>
<toOverride>false</toOverride>
<toDefault>true</toDefault>
<from></from>
<fromOverride>false</fromOverride>
<fromDefault>true</fromDefault>
<action></action>
<actionOverride>false</actionOverride>
<actionDefault>true</actionDefault>
<msgid></msgid>
<msgidOverride>false</msgidOverride>
<msgidDefault>true</msgidDefault>
<replyTo></replyTo>
<replyToOverride>false</replyToOverride>
<faultTo></faultTo>
<faulttToOverride>false</faulttToOverride>
<addressingVersion>http://www.w3.org/2005/08/addressing</addressingVersion>
</wsaInfo>
<customHTTPHeaderInfo>
</customHTTPHeaderInfo>
<useDefaultNamespace>true</useDefaultNamespace>
<forceNoWrap>false</forceNoWrap>
<uddi-lookup>false</uddi-lookup>
    </Node>


    <Node name="Step 4: Fail: Missing Signature" log=""
          type="com.itko.lisa.dynexec.axis.WebServiceNode" 
          version="1" 
          think="0" 
          useFilters="true" 
          quiet="false" 
          next="fail" > 

<Documentation>This step is designed to fail because we send an unsigned SOAP request</Documentation>

      <!-- Assertions -->
<CheckResult assertTrue="true" name="Any Exception Then Fail" type="com.itko.lisa.dynexec.CheckInvocationEx">
<log>Assert [Any Exception Then Fail] fired true of type Assert on Invocation Exception</log>
<then>fail</then>
<valueToAssertKey></valueToAssertKey>
        <param>.*</param>
</CheckResult>

<className>com.itko.lisa.wsgen.SignedCalculatorService.CalculatorServiceLocator</className>
<onExNode>end</onExNode>
<WSDL>http://{{WSSERVER}}:{{WSPORT}}/itko-examples/services/SignedCalculatorService?wsdl</WSDL>
<Package>com.itko.lisa.wsgen.SignedCalculatorService</Package>
<ClientJar>SignedCalculatorService.jar</ClientJar>
<SOAPBindAddr>http://{{WSSERVER}}:{{WSPORT}}/itko-examples/services/SignedCalculatorService</SOAPBindAddr>
<objStream>
<DynObject>
<type>com.itko.lisa.dynexec.ComplexObj</type>
<serialNum>0</serialNum>
<array>false</array>
<className>com.itko.lisa.wsgen.SignedCalculatorService.CalculatorServiceLocator</className>
<complex>true</complex>
<interface>false</interface>
<null>false</null>
<void>false</void>
<simple>false</simple>
<useprop>false</useprop>
<Setters>
</Setters>
<Call>
<methodName>getSignedCalculatorService</methodName>
<retClassName>com.itko.lisa.wsgen.SignedCalculatorService.Calculator</retClassName>
<actParamClassName>java.net.URL</actParamClassName>
<paramClassName>java.net.URL</paramClassName>
<exClassName>javax.xml.rpc.ServiceException</exClassName>
<param>
<DynObject>
<type>com.itko.lisa.dynexec.ComplexObj</type>
<serialNum>3</serialNum>
<array>false</array>
<className>java.net.URL</className>
<complex>true</complex>
<interface>false</interface>
<null>false</null>
<void>false</void>
<simple>false</simple>
<useprop>true</useprop>
<propKey>itkolisa.WebServiceNode.hiddenBindAddrKey</propKey>
<Setters>
</Setters>
</DynObject>
</param>
<result>
<DynObject>
<type>com.itko.lisa.dynexec.ComplexObj</type>
<serialNum>4</serialNum>
<array>false</array>
<className>com.itko.lisa.wsgen.SignedCalculatorService.SignedCalculatorServiceSoapBindingStub</className>
<complex>true</complex>
<interface>false</interface>
<null>false</null>
<void>false</void>
<simple>false</simple>
<useprop>false</useprop>
<Setters>
</Setters>
<Call>
<methodName>add</methodName>
<retClassName>java.lang.Integer</retClassName>
<actParamClassName>int</actParamClassName>
<actParamClassName>int</actParamClassName>
<paramClassName>java.lang.Integer</paramClassName>
<paramClassName>java.lang.Integer</paramClassName>
<exClassName>java.rmi.RemoteException</exClassName>
<param>
<DynObject>
<type>com.itko.lisa.dynexec.SimpleObj</type>
<serialNum>6</serialNum>
<array>false</array>
<className>java.lang.Integer</className>
<complex>false</complex>
<interface>false</interface>
<null>false</null>
<void>false</void>
<simple>true</simple>
<useprop>false</useprop>
<simpleVal>4</simpleVal>
</DynObject>
</param>
<param>
<DynObject>
<type>com.itko.lisa.dynexec.SimpleObj</type>
<serialNum>7</serialNum>
<array>false</array>
<className>java.lang.Integer</className>
<complex>false</complex>
<interface>false</interface>
<null>false</null>
<void>false</void>
<simple>true</simple>
<useprop>false</useprop>
<simpleVal>3</simpleVal>
</DynObject>
</param>
<result>
<DynObject>
<type>com.itko.lisa.dynexec.SimpleObj</type>
<serialNum>5</serialNum>
<array>false</array>
<className>java.lang.Integer</className>
<complex>false</complex>
<interface>false</interface>
<null>false</null>
<void>false</void>
<simple>true</simple>
<useprop>false</useprop>
<simpleVal>9</simpleVal>
</DynObject>
</result>
<isCallMade>false</isCallMade>
</Call>
</DynObject>
</result>
<isCallMade>false</isCallMade>
</Call>
</DynObject>
</objStream>
<wsGlobalInfo>
<soapVersionUri>1.1</soapVersionUri>
<httpVersionUri>1.1</httpVersionUri>
<webMethodUri>POST</webMethodUri>
<mtom>false</mtom>
<dontSendRequest>false</dontSendRequest>
<dontDeserialze>false</dontDeserialze>
<allowNonNillable>false</allowNonNillable>
<callTimeout>600000</callTimeout>
<wsi-check-wsdl>false</wsi-check-wsdl>
<wsi-check-msg>false</wsi-check-msg>
<wsi-display-type>notPassed</wsi-display-type>
<wsi-on-fail>continue</wsi-on-fail>
<ssl-keystore-file></ssl-keystore-file>
<ssl-keystore-password-enc>f5504e2d23a7888253a27e8ef52607d8</ssl-keystore-password-enc>
</wsGlobalInfo>
<wss4jInfo>
<version>5</version>
<wssecurity>
<isSend>true</isSend>
<must>false</must>
<timestamp2>
<enabled>false</enabled>
<useMsTimestamp>true</useMsTimestamp>
<ttl>300</ttl>
</timestamp2>
<usernameToken>
<enabled>false</enabled>
<type>PasswordText</type>
<signed>false</signed>
<nonce>true</nonce>
<craeted>true</craeted>
<useMsTimestamp>true</useMsTimestamp>
</usernameToken>
<signature>
<enabled>false</enabled>
<file>{{LISA_PROJ_ROOT}}/Data/keystores/keystore.jks</file>
<type>jks</type>
<password-encr>d32b9ba6faca78de7b32314e43c15b4f</password-encr>
<defaultalias>test</defaultalias>
<alias-pass-encr>d32b9ba6faca78de7b32314e43c15b4f</alias-pass-encr>
<keyId>IssuerSerial</keyId>
<algo>http://www.w3.org/2000/09/xmldsig#dsa-sha1</algo>
</signature>
<encryption>
<enabled>false</enabled>
<type>jks</type>
<password-encr>f5504e2d23a7888253a27e8ef52607d8</password-encr>
<alias-pass-encr>f5504e2d23a7888253a27e8ef52607d8</alias-pass-encr>
<keyId>IssuerSerial</keyId>
<algo>http://www.w3.org/2001/04/xmlenc#aes128-cbc</algo>
<transport>http://www.w3.org/2001/04/xmlenc#rsa-1_5</transport>
</encryption>
</wssecurity>
<wssecurity>
<isSend>false</isSend>
<must>false</must>
</wssecurity>
<wsi-bsp>false</wsi-bsp>
</wss4jInfo>
<GenericHeader>
<ns>
</ns>
<xml></xml>
</GenericHeader>
<wsaInfo>
<useAddressing>false</useAddressing>
<must>false</must>
<to></to>
<toOverride>false</toOverride>
<toDefault>true</toDefault>
<from></from>
<fromOverride>false</fromOverride>
<fromDefault>true</fromDefault>
<action></action>
<actionOverride>false</actionOverride>
<actionDefault>true</actionDefault>
<msgid></msgid>
<msgidOverride>false</msgidOverride>
<msgidDefault>true</msgidDefault>
<replyTo></replyTo>
<replyToOverride>false</replyToOverride>
<faultTo></faultTo>
<faulttToOverride>false</faulttToOverride>
<addressingVersion>http://www.w3.org/2005/08/addressing</addressingVersion>
</wsaInfo>
<customHTTPHeaderInfo>
</customHTTPHeaderInfo>
<useDefaultNamespace>true</useDefaultNamespace>
<forceNoWrap>false</forceNoWrap>
<uddi-lookup>false</uddi-lookup>
    </Node>


    <Node name="fail" log=""
          type="com.itko.lisa.test.Abend" 
          version="1" 
          think="0-0" 
          useFilters="true" 
          quiet="true" 
          next="" > 

    </Node>


    <Node name="end" log=""
          type="com.itko.lisa.test.NormalEnd" 
          version="1" 
          think="0-0" 
          useFilters="true" 
          quiet="true" 
          next="fail" > 

    </Node>


    <Node name="abort" log=""
          type="com.itko.lisa.test.AbortStep" 
          version="1" 
          think="0h" 
          useFilters="true" 
          quiet="true" 
          next="end" > 

    </Node>


</TestCase>
